name: frontend-cicd
on:
  push:
  workflow_dispatch:
jobs:
  frontend-ci:
    uses: linga-devsecops-actions/14.12.github-actions-expense-reusable-workflows/.github/workflows/nginx-common.yaml@main
    with:
      project: expense
      component: frontend
      environment: dev
      app_type: web
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
